# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: op-interface.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='op-interface.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12op-interface.proto\"F\n\x1aOrienteeringProblemRequest\x12\x14\n\x05items\x18\x01 \x03(\x0b\x32\x05.Item\x12\x12\n\ntime_limit\x18\x02 \x01(\x01\"=\n\x1bOrienteeringProblemResponse\x12\x1e\n\x0f\x63ollected_items\x18\x01 \x03(\x0b\x32\x05.Item\"\x1c\n\x04Item\x12\t\n\x01x\x18\x01 \x01(\r\x12\t\n\x01y\x18\x02 \x01(\r2e\n\x1aOrienteeringProblemService\x12G\n\x08Optimize\x12\x1b.OrienteeringProblemRequest\x1a\x1c.OrienteeringProblemResponse\"\x00\x62\x06proto3'
)




_ORIENTEERINGPROBLEMREQUEST = _descriptor.Descriptor(
  name='OrienteeringProblemRequest',
  full_name='OrienteeringProblemRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='OrienteeringProblemRequest.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time_limit', full_name='OrienteeringProblemRequest.time_limit', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=92,
)


_ORIENTEERINGPROBLEMRESPONSE = _descriptor.Descriptor(
  name='OrienteeringProblemResponse',
  full_name='OrienteeringProblemResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='collected_items', full_name='OrienteeringProblemResponse.collected_items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=155,
)


_ITEM = _descriptor.Descriptor(
  name='Item',
  full_name='Item',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='Item.x', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='Item.y', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=157,
  serialized_end=185,
)

_ORIENTEERINGPROBLEMREQUEST.fields_by_name['items'].message_type = _ITEM
_ORIENTEERINGPROBLEMRESPONSE.fields_by_name['collected_items'].message_type = _ITEM
DESCRIPTOR.message_types_by_name['OrienteeringProblemRequest'] = _ORIENTEERINGPROBLEMREQUEST
DESCRIPTOR.message_types_by_name['OrienteeringProblemResponse'] = _ORIENTEERINGPROBLEMRESPONSE
DESCRIPTOR.message_types_by_name['Item'] = _ITEM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OrienteeringProblemRequest = _reflection.GeneratedProtocolMessageType('OrienteeringProblemRequest', (_message.Message,), {
  'DESCRIPTOR' : _ORIENTEERINGPROBLEMREQUEST,
  '__module__' : 'op_interface_pb2'
  # @@protoc_insertion_point(class_scope:OrienteeringProblemRequest)
  })
_sym_db.RegisterMessage(OrienteeringProblemRequest)

OrienteeringProblemResponse = _reflection.GeneratedProtocolMessageType('OrienteeringProblemResponse', (_message.Message,), {
  'DESCRIPTOR' : _ORIENTEERINGPROBLEMRESPONSE,
  '__module__' : 'op_interface_pb2'
  # @@protoc_insertion_point(class_scope:OrienteeringProblemResponse)
  })
_sym_db.RegisterMessage(OrienteeringProblemResponse)

Item = _reflection.GeneratedProtocolMessageType('Item', (_message.Message,), {
  'DESCRIPTOR' : _ITEM,
  '__module__' : 'op_interface_pb2'
  # @@protoc_insertion_point(class_scope:Item)
  })
_sym_db.RegisterMessage(Item)



_ORIENTEERINGPROBLEMSERVICE = _descriptor.ServiceDescriptor(
  name='OrienteeringProblemService',
  full_name='OrienteeringProblemService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=187,
  serialized_end=288,
  methods=[
  _descriptor.MethodDescriptor(
    name='Optimize',
    full_name='OrienteeringProblemService.Optimize',
    index=0,
    containing_service=None,
    input_type=_ORIENTEERINGPROBLEMREQUEST,
    output_type=_ORIENTEERINGPROBLEMRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ORIENTEERINGPROBLEMSERVICE)

DESCRIPTOR.services_by_name['OrienteeringProblemService'] = _ORIENTEERINGPROBLEMSERVICE

# @@protoc_insertion_point(module_scope)
