# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import op_interface_pb2 as op__interface__pb2


class OrienteeringProblemServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Optimize = channel.unary_unary(
                '/OrienteeringProblemService/Optimize',
                request_serializer=op__interface__pb2.OrienteeringProblemRequest.SerializeToString,
                response_deserializer=op__interface__pb2.OrienteeringProblemResponse.FromString,
                )


class OrienteeringProblemServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Optimize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrienteeringProblemServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Optimize': grpc.unary_unary_rpc_method_handler(
                    servicer.Optimize,
                    request_deserializer=op__interface__pb2.OrienteeringProblemRequest.FromString,
                    response_serializer=op__interface__pb2.OrienteeringProblemResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'OrienteeringProblemService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class OrienteeringProblemService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Optimize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/OrienteeringProblemService/Optimize',
            op__interface__pb2.OrienteeringProblemRequest.SerializeToString,
            op__interface__pb2.OrienteeringProblemResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
