// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: op-interface.proto

#include "op-interface.pb.h"
#include "op-interface.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>

static const char* OrienteeringProblemService_method_names[] = {
  "/OrienteeringProblemService/Optimize",
};

std::unique_ptr< OrienteeringProblemService::Stub> OrienteeringProblemService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< OrienteeringProblemService::Stub> stub(new OrienteeringProblemService::Stub(channel));
  return stub;
}

OrienteeringProblemService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_Optimize_(OrienteeringProblemService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status OrienteeringProblemService::Stub::Optimize(::grpc::ClientContext* context, const ::OrienteeringProblemRequest& request, ::OrienteeringProblemResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Optimize_, context, request, response);
}

void OrienteeringProblemService::Stub::experimental_async::Optimize(::grpc::ClientContext* context, const ::OrienteeringProblemRequest* request, ::OrienteeringProblemResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Optimize_, context, request, response, std::move(f));
}

void OrienteeringProblemService::Stub::experimental_async::Optimize(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::OrienteeringProblemResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Optimize_, context, request, response, std::move(f));
}

void OrienteeringProblemService::Stub::experimental_async::Optimize(::grpc::ClientContext* context, const ::OrienteeringProblemRequest* request, ::OrienteeringProblemResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Optimize_, context, request, response, reactor);
}

void OrienteeringProblemService::Stub::experimental_async::Optimize(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::OrienteeringProblemResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Optimize_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::OrienteeringProblemResponse>* OrienteeringProblemService::Stub::AsyncOptimizeRaw(::grpc::ClientContext* context, const ::OrienteeringProblemRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::OrienteeringProblemResponse>::Create(channel_.get(), cq, rpcmethod_Optimize_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::OrienteeringProblemResponse>* OrienteeringProblemService::Stub::PrepareAsyncOptimizeRaw(::grpc::ClientContext* context, const ::OrienteeringProblemRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::OrienteeringProblemResponse>::Create(channel_.get(), cq, rpcmethod_Optimize_, context, request, false);
}

OrienteeringProblemService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      OrienteeringProblemService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< OrienteeringProblemService::Service, ::OrienteeringProblemRequest, ::OrienteeringProblemResponse>(
          [](OrienteeringProblemService::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::OrienteeringProblemRequest* req,
             ::OrienteeringProblemResponse* resp) {
               return service->Optimize(ctx, req, resp);
             }, this)));
}

OrienteeringProblemService::Service::~Service() {
}

::grpc::Status OrienteeringProblemService::Service::Optimize(::grpc::ServerContext* context, const ::OrienteeringProblemRequest* request, ::OrienteeringProblemResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


